services:
  my_zookeeper:
    image: zookeeper:latest
    container_name: my_zookeeper
    ports:
      - "2181:2181"

  my_kafka:
    image: confluentinc/cp-kafka:latest
    container_name: my_kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: my_zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INSIDE://my_kafka:9092,OUTSIDE://192.168.29.98:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
